### PR TITLE
`display_width`: ignore ANSI hyperlinks in width calculation

### PR DESCRIPTION
**Pull request by tertsdiepraam**
Closes https://github.com/mgeisler/textwrap/issues/525

I've attempted to keep the implementation similar to the current implementation and added a simple test for it. This keeps it in a bit of an awkward state (e.g. comparing with `CSI.1` in one branch and `']'` in the other). Happy to take suggestions for the direction to take this PR!

### CODE REVIEW

**Comment by anthraxx** [comment]
I was actually hit by this bug and found this PR. @mgeisler any chance you can take a look :cat:

**Comment by tertsdiepraam** [comment]
I added support for a BEL character as separator between the link and the text. This is used by some programs such as GNU `ls` and therefore also uutils `ls`. Since this PR has not seen any activity, I'll be moving uutils to my own crate, but I figured I would still fix the same issue here. I think it would still be nice for the community to have this PR merged!

**Review by mgeisler — APPROVED** [review]
Thanks a lot for this!

**Comment by mgeisler** [comment]
Thanks for the ping! I'm sorry I had forgotten about this... let's merge it right away so I can make a new release.

**Comment by tertsdiepraam** [comment]
Thanks!

**Comment by mgeisler** [comment]
I finally got around to merge the release PR: #533 and this means 0.16.1 is available!

**Pull request merged**
