### PR TITLE
lib: ignore ANSI escape sequences

### PR DESCRIPTION
**Pull request by mgeisler**
ANSI escape sequences are typically used for colored text. The
sequences start with a so-called CSI, followed by some "parameter
bytes" before ending with a "final byte".

We now handle these escape sequences by simply skipping over the
bytes. This works well for escape sequences that change colors since
they don't take up space and since they continue to work across any
line breaks we insert.

See https://en.wikipedia.org/wiki/ANSI_escape_code for details.

Fixes: #140.

### CODE REVIEW

**Comment by mgeisler** [comment]
@pksunkara, would you be able to do a test with this commit and tell me if this solves your problem in  clap-rs/clap#1246?

**Comment by mgeisler** [comment]
This PR will of course not do anything sensible for Windows. As far as I understand, colored text depends on using special Windows APIs and so I guess the color information isn't embedded into the string like on Linux?

**Comment by pksunkara** [comment]
I can't say because we refactored our color writing and we don't construct strings anymore but write directly to `io`. So, all the strings we now give to textwrap are plain.

**Comment by mgeisler** [comment]
Aha, I thought based on https://github.com/clap-rs/clap/issues/1246 and https://github.com/mgeisler/textwrap/issues/140#issuecomment-612460117 that `clap` was needing this feature? I was hoping you could test it for me to help guide it and make sure it's useful.

**Comment by mgeisler** [comment]
I'll merge it right after I fix Travis -- my crate has again stopped building on Rust 1.31.0.

**Comment by pksunkara** [comment]
Yeah, we will probably need it again when we are fixing https://github.com/clap-rs/clap/issues/1456. But, unfortunately, it is not a priority until after we release 3.0

**Comment by mgeisler** [comment]
Okay, cool! I'll get a release out of textwrap in the meantime and then I hope it'll be useful for you guys.

**Comment by pksunkara** [comment]
Before you release, do you think you can port this to https://lib.rs/crates/terminal_size? `term_size` is not being maintained and I would appreciate if you could port it to a more maintained version.

**Comment by mgeisler** [comment]
Sure, let me update that right away.

**Pull request merged**
